---
# roles/pg_install/tasks/offline_repo.yml

- name: check centos repos
  stat: 
    path: /etc/yum.repos.d/CentOS-Base.repo
  register: centosrepo

- name: centos repos removed
  shell: 
    cmd: mkdir -p /etc/yum.repos.d/repobkp ; mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/repobkp
    warn: false
  when: centosrepo.stat.exists

- name: postgres repo copied
  unarchive:
    src: pgrepo_centos7.tgz
    dest: /opt/

#  - name: Copy Postgres repo
#    synchronize:
#      src: ../repos/pgrepo
#      dest: /opt
#      compress: no

- name: pg repo added
  copy:
    dest: /etc/yum.repos.d/local-pg.repo
    content: | 
      [pg12-local]
      name=PostgreSQL 12 Local Repo
      baseurl=file:///opt/pgrepo
      enabled=1
      gpgcheck=0
