---
#file: roles/pg_stearming/tasks/main.ym
- import_tasks: config_pgmaster12.yml
  become: true
  when: ansible_eth1.ipv4.address == MASTER_IP
  tags: 
  - pg_rep
  - pg_rep_master

- meta: flush_handlers
  tags:
  - pg_rep

- import_tasks: config_pgslave12.yml
  become: true
  when: ansible_eth1.ipv4.address == SLAVE1_IP 
     or ansible_eth1.ipv4.address == SLAVE2_IP
  tags:
  - pg_rep
  - pg_rep_slave

- import_tasks: config_sync.yml
  become: true
  when: REPLICATION_TYPE == 'synchronous'
  tags: 
  - pg_rep

- name: update primary slot name
  become: true
  lineinfile:
    path: "{{ PGDATA }}/postgresql.conf"
    regexp: '{{item.From}}'
    line: '{{item.To}}'
  with_items:
    - { From: "#primary_slot_name = ''", To: "primary_slot_name = '{{ 'node' + ansible_eth1.ipv4.address.split('.')[3] }}'" }
  when: REPLICATION_SLOT
  notify: restart postgres
  tags:
  - pg_rep