#!/usr/bin/ansible-playbook
---
- hosts: all
  gather_facts: no
  become: true
  vars_files: vars.yml
  pre_tasks:
  - timezone:
      name: 'Asia/Kolkata'
    tags: [ 'time' ]
  - import_tasks: tasks/local_repo.yml
    tags: ['repo']
  - import_tasks: tasks/clean.yml
    tags: [ 'never', 'clean' ]
    ignore_errors: yes
  
- hosts: pg_repl
  gather_facts: no
  become: true
  vars_files: vars.yml
  roles:
  - postgres-replication
  - postgres-edb_efm
  

