#!/usr/bin/ansible-playbook
---
- hosts: pgcluster
  
  vars:
    # Postgres 
    PGDATA: /srv/pgdata
    PGUSER: postgres
    PGPASS: Postgres@123    
    # replication
    REPLICATION_TYPE: synchronous
    # EFM
    EFM_VIP: 192.168.33.10

  # Cleans previous configuration when "--tags clean"  
  pre_tasks:
  - ping:
    tags: ping  
  - import_tasks: clean.yml
    become: true
    tags: [ 'never', 'clean' ]

  roles:
  - postgres-edb_efm
