#!/usr/bin/ansible-playbook
---
- hosts: pg_cluster
  
  vars:
    # Postgres 
    PGDATA: /srv/pgdata
    PGUSER: postgres
    PGPASS: Postgres@123    
    # VIP
    EFM_VIP: 192.168.33.10
    # replication
    REPLICATION_TYPE: synchronous

  pre_tasks:
  - import_tasks: clean.yml
    become: true
    tags:
    - never
    - clean

  roles:
  - postgres-edb_efm

  