#!/usr/bin/ansible-playbook
---
- hosts: pgcluster
  
  vars:
    # Postgres 
    PGDATA: /srv/pgdata
    PGUSER: postgres
    PGPASS: Postgres@123    
    # replication
    REPLICATION_TYPE: synchronous
    # EFM
    EFM_VIP: 192.168.33.10

  
  pre_tasks:
  # Simple ping to check
  - timezone:
      name: 'Asia/Kolkata'
    become: true
    tags: [ 'time' ]
  # Cleans previous configuration when "--tags clean"
  - import_tasks: clean.yml
    become: true
    tags: [ 'never', 'clean' ]

  roles:
  - postgres-edb_efm
