#!/usr/bin/ansible-playbook
---
- hosts: pg_repl
  gather_facts: no
  become: true
  vars:   
    PGDATA: /srv/pgdata
  pre_tasks:
  - import_role: 
      name: lxd_inventory
  - import_tasks: local_repo.yml
  roles:
  - postgres-replication
  - postgres-edb_efm
  
  
