#!/usr/bin/ansible-playbook
---
- hosts: pgcluster
  gather_facts: no
  
  vars:
    # Postgres 
    PGDATA: /srv/pgdata
    PGUSER: postgres
    PGPASS: Postgres@123    
    # replication
    PG_REP_GRP: pgcluster
    REPLICATION_SLOT: True 
    REPLICATION_TYPE: synchronous
    # EFM
    EFM_VIP: 192.168.33.10

  pre_tasks:
  # Simple ping to check
  - timezone:
      name: 'Asia/Kolkata'
    become: true
    tags: [ 'time' ]
  - import_tasks: tasks/local_repo.yml
    become: true
    tags: ['repo']
  # Cleans previous configuration when "--tags clean"
  - import_tasks: tasks/clean.yml
    become: true
    tags: [ 'never', 'clean' ]

  roles:
  - postgres-edb_efm
