---
# file: roles/pg_straming/defaults/main.yml

# Replication
REPLICATION_SLOT: False          #/True
REPLICATION_TYPE: synchronous    #/asynchronous
REPLICATION_USER: replicator
REPLICATION_PASS: raplicator@123
