#!/usr/bin/ansible-playbook
---
#- hosts: all
#  gather_facts: no
#  become: true
#  vars_files: vars.yml
#  tasks:

  - systemd:
      name: edb-efm-3.10
      state: stopped

  - file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/edb/efm-3.10/efm.nodes
    - /etc/edb/efm-3.10/efm.properties
    - /var/log/efm-3.10/efm.log
    - /var/log/efm-3.10/startup-efm.log
  
  - systemd:
      name: postgresql-12
      state: stopped

  - file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "{{ PGDATA }}"
    - "/backup"
      
