#file: tasks/clean.yml
---

# Clean EFM
- systemd:
    name: "edb-efm-{{ EFM_VERSION }}"
    state: stopped
- file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/edb/efm-{{ EFM_VERSION }}/efm.nodes"
  - "/etc/edb/efm-{{ EFM_VERSION }}/efm.properties"
  - "/var/log/efm-{{ EFM_VERSION }}/efm.log"
  - "/var/log/efm-{{ EFM_VERSION }}/startup-efm.log"

# Clean PostgreSQL
- systemd:
    name: "postgresql-{{ PGVER }}"
    state: stopped
- file:
    path: "{{ PGDATA }}"
    state: absent


#  with_items:
#  - "{{ PGDATA }}"
#  - "/backup"
#    - "/opt/repos/repodata"
      
