---
# roles/pg_install/tasks/offline_repo.yml

- name: check centos repos
  stat: 
    path: /etc/yum.repos.d/CentOS-Base.repo
  register: centosrepo

- name: centos repos removed
  shell: 
    cmd: mkdir -p /etc/yum.repos.d/repobkp ; mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/repobkp
    warn: false
  when: centosrepo.stat.exists

- name: postgres repo copied
  unarchive:
    src: repos.tgz
    dest: /opt/
    creates: /opt/repos/repodata/repomd.xml

- name: pg repo added
  copy:
    dest: /etc/yum.repos.d/local.repo
    mode: 0644
    content: | 
      [local-repo]
      name=Local Repo
      baseurl=file:///opt/repos
      enabled=1
      gpgcheck=0
