---
- name: Create lxd containers
  lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocal: simplestreams
      alias: "{{ os_image | default('centos/7/amd64') }}"
  delegate_to: 127.0.0.1
  tags: lxd
- package:
    state: present
    name: which
    use: auto 
  tags: lxd
- name: Remove Containers
  block:
  - lxd_container:
      name: "{{ inventory_hostname }}"
      state: absent
    delegate_to: 127.0.0.1
  - fail: msg="Containers Removed"
  tags: ['never', 'lxd_clean']
