---
#file: roles/postgres-install/tasks/install_pgdb{{ PGVER }}.yml

- name: Install postgres {{ PGVER }} server
  yum:
    name: "{{ packages }}"
  vars:
    packages: 
      - "postgresql{{ PGVER }}-server"
      - "postgresql{{ PGVER }}"
    state: present   
      
- name: Install python pip and psycopg2
  yum:
    name: [ 'python-pip', 'python-psycopg2' ]
    state: present    

- name: Copy postgres systemd file
  copy:
    dest: "/etc/systemd/system/postgresql-{{ PGVER }}.service"  
    src: "/usr/lib/systemd/system/postgresql-{{ PGVER }}.service"
    mode: preserve
    force: no
    remote_src: yes

- name: set postgres data path
  replace:
    path: "/etc/systemd/system/postgresql-{{ PGVER }}.service"
    regexp: ^Environment=PGDATA=.+$  
    replace: "Environment=PGDATA={{ PGDATA }}/" 

- name: Configure postgres {{ PGVER }}
  shell:
    creates: "{{ PGDATA }}/postgresql.conf" 
    cmd: /usr/pgsql-{{ PGVER }}/bin/postgresql-{{ PGVER }}-setup initdb     
#  - name: Configure postgres {{ PGVER }} if default user is not postgres 
#    shell:
#      creates: "{{ PGDATA }}/postgresql.conf" 
#      cmd: sudo /sbin/runuser -l postgres -c '/usr/pgsql-{{ PGVER }}/bin/initdb -U {{PGUSER}} -D {{ PGDATA }}'
#      warn: false
#    when: PGUSER != 'postgres'

- name: Allow local login as trust 
  postgresql_pg_hba:
    dest: "{{ PGDATA }}/pg_hba.conf"
    contype: local
    method: trust

- name: Allow local login as trust for host ipv4 & ipv6
  postgresql_pg_hba:
    dest: "{{ PGDATA }}/pg_hba.conf"
    contype: host
    method: trust
    source: "{{ item }}"
  with_items:
    - "127.0.0.1/32"
    - "::1/128"  

- name: Start DB Service
  systemd: 
     name: "postgresql-{{ PGVER }}"
     state: started
     enabled: yes

- name: Create directory for backup
  file:
    path: /backup
    state: directory
    owner: postgres

- name: Reset '{{PGUSER}}' password
  postgresql_user:
    name: "{{ PGUSER }}"
    password: "{{ PGPASS }}"
  no_log: true