--- 

#- name: Create pgpass file
#  lineinfile:
#    path: /var/lib/pgsql/.pgpass
#    line: "*:5432:*:{{ REPLICATION_USER }}:{{ REPLICATION_PASS }}"
#    create: yes
#    owner: postgres
#    group: postgres
#    mode: '0600'

- name: check if standby
  stat: 
    path: "{{ PGDATA }}/standby.signal"
  register: standby

- name: initialize slave
  block:

  - name: db stopped
    systemd:
      name: postgresql-12
      state: stopped
  
  - name: pgdata directory deleted
    file:
      path: "{{ PGDATA }}"
      state: absent
  
#  - name: pg_basebackup cmd with replication slot
#    set_fact:
#      pg_basebackup_cmd: "{{ pg_basebackup_cmd + ' --slot=slot' + pg_repl_id|string }}" 
#    when: REPLICATION_SLOT

  - name: pg_basebackup from {{ pg_master_ip }}
    shell: 
      cmd: | 
        PGAPPNAME="{{ 'node' + pg_repl_id|string }}" \
        PGPASSWORD="{{ REPLICATION_PASS }}" \
        {{ pg_basebackup_cmd }} --username={{ REPLICATION_USER }} \
        --host="{{ pg_master_ip }}" --port=5432  
  
  - name: data directory are set
    file:
      path: "{{ PGDATA }}"
      state: directory
      owner: postgres
      group: postgres
      recurse: yes
  
  - name: db started
    systemd:
     name: postgresql-12
     state: started
     enabled: yes

  when: not standby.stat.exists
