---

- name: set synchronous_standby names
  set_fact:
    standby_names: "{{ pg_repl_nodes_ids | join(',') | 
      regex_replace('([0-9]{1})', 'node\\1') }}"
    
- name: synchronous commit and standby names
  become: true
  postgresql_set: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
  - { name: synchronous_commit, value: "on" }
  - { name: synchronous_standby_names, value: "any 1 ({{standby_names}})" }
