---
#file: roles/pg_stearming/tasks/main.ym

- import_tasks: config_pgmaster12.yml
  become: true
  when: pg_repl_role == 'master'
  tags: 
  - pg_rep
  - pg_rep_master

- meta: flush_handlers
  tags:
  - pg_rep

- import_tasks: config_pgslave12.yml
  become: true
  when: pg_repl_role == 'standby'
  tags:
  - pg_rep
  - pg_rep_slave

- import_tasks: set_synchronous_repl.yml
  become: true
  when: REPLICATION_TYPE == 'synchronous'
  tags: 
  - pg_rep
  - pg_rep_sync

- name: update primary slot name
  become: true
  lineinfile:
    path: "{{ PGDATA }}/postgresql.conf"
    regexp: '{{item.From}}'
    line: '{{item.To}}'
  with_items:
    - { From: "#primary_slot_name = ''", To: "primary_slot_name = '{{ 'slot' + pg_repl_id|string }}'" }
  when: REPLICATION_SLOT
  notify: restart postgres
  tags:
  - pg_rep