---
#file: roles/pg_stearming/tasks/main.ym

- name: debug
  block:
  - debug: var=pg_master_ip
  - debug: var=pg_repl_nodes_ips
  - debug: var=pg_repl_nodes_ids
  tags: ['debug','never']  

- import_tasks: config_pgmaster.yml
  become: true
  when: pg_repl_role == 'master'
  tags: 
  - pg_rep
  - pg_rep_master

- meta: flush_handlers
  tags:
  - pg_rep

- import_tasks: config_pgslave.yml
  become: true
  when: pg_repl_role == 'standby'
  tags:
  - pg_rep
  - pg_rep_slave

- import_tasks: config_sync_repl.yml
  become: true
  when: REPLICATION_TYPE == 'synchronous'
  tags: 
  - pg_rep
  - pg_rep_sync

- name: update primary slot name
  become: true
  lineinfile:
    path: "{{ PGDATA }}/postgresql.conf"
    regexp: '{{item.From}}'
    line: '{{item.To}}'
  with_items:
    - { From: "#primary_slot_name = ''", To: "primary_slot_name = '{{ 'slot' + pg_repl_id|string }}'" }
  when: REPLICATION_SLOT
  notify: restart postgres
  tags:
  - pg_rep