---
#file: roles/pg_stearming/tasks/main.ym
- name: nodeips
  setup:
    gather_subset: network
 
- name: debug
  block:
  - debug: var=pg_repl_role
  - debug: var=pg_repl_id
  - debug: var=pg_master_ip
  - debug: var=pg_repl_nodes_ips
  - debug: var=pg_repl_nodes_ids
  tags: ['debug','never']  

- import_tasks: config_pgmaster.yml
  become: true
  when: pg_repl_role == 'master'
  tags: 
  - pg_rep
  - pg_rep_master

- meta: flush_handlers
  tags:
  - pg_rep

- import_tasks: config_pgslave.yml
  become: true
  when: pg_repl_role == 'standby'
  tags:
  - pg_rep
  - pg_rep_slave

- import_tasks: config_sync_repl.yml
  become: true
  when: REPLICATION_TYPE == 'synchronous'
  tags:  
  - pg_rep
  - pg_rep_sync

- name: update connection for replication slots
  become: true
  postgresql_set: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
  - name: primary_slot_name
    value: "{{ 'slot' + pg_repl_id|string }}"
  - name: primary_conninfo
    value: >-
      user={{ REPLICATION_USER }} password={{ REPLICATION_PASS }} 
      host={{ pg_master_ip }} port=5432 application_name={{ 'node' + pg_repl_id|string  }}
      sslmode=prefer sslcompression=0 gssencmode=prefer krbsrvname=postgres target_session_attrs=any
  when: REPLICATION_SLOT
  notify: restart postgres
  tags:
    - pg_rep
