- name: created lxd container
  lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    source:
      type: image
      mode: pull
      server: "{{ lxc_img_server | default(omit) }}"
      protocal: "{{ lxc_img_server_protocal | default(omit) }}"
      alias: "{{ lxc_alias }}"
    devices:
      eth0:
        type: nic
        nictype: bridged
        parent: lxdbr0
        ipv4.address: "{{ ip }}"
    wait_for_ipv4_addresses: yes
  delegate_to: 127.0.0.1
