- name: created lxd container
  lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocal: simplestreams
      alias: "{{ os_image | default('centos/7/amd64') }}"
    devices:
      eth0:
        type: nic
        nictype: bridged
        parent: lxdbr0
        ipv4.address: "{{ ip }}"
    wait_for_ipv4_addresses: yes
  delegate_to: 127.0.0.1
