---
# file: roles/edb_efm/default/main.yml
edb_repo: True
#edb_repo_user: 
#edb_repo_pass:

# PG Details
PGVER: 12
PGDATA: /var/lib/pgsql/{{ PGVER }}/data

# EFM Details
EFM_VERSION: '4.0'
EFM_USER: efm
EFM_USER_PASSWORD: efm@123
NOTIFICATION_EMAIL: fssai.cdc@gmail.com


EFM_GRP: edb_efm

efm_nodes_ips: "{{ groups[EFM_GRP] | 
  map('extract', hostvars, ['ansible_default_ipv4','address']) | list }}"
EFM_VIP: "{{ (ansible_default_ipv4.network 
  + '/' + ansible_default_ipv4.netmask) | ipaddr(10) }}"
