version: "3"

services:
  centosrepo:
    image: pkgs
    build:
      context: .
      args: 
        EDB_USER: ${EDB_USER}
        EDB_PASS: ${EDB_PASS}
    command: tar -czvf /pkgs/repos.tgz /repos
    volumes: 
    - "./:/pkgs"