---
# file: roles/edb_efm/handlers/main.yml
- name: restart efm
  become: true
  systemd:
    name: "edb-efm-{{ EFM_VERSION }}"
    state: restarted

# Reload Postgres
- name: reload postgres
  become: true
  systemd:
    name: "postgresql-{{ PGVER }}"
    state: reloaded