---
#file: roles/postgres-replication/vars/main.yml

# master ip
pg_master_ip: "{% for node in ansible_play_hosts_all %}\
  {% if hostvars[node].pg_repl_role == 'master' %}\
  {{ hostvars[node].ansible_eth1.ipv4.address }}\
  {% endif %}{% endfor %}"

# list of replication nodes
pg_replication_nodes: "{{ ansible_play_hosts_all | 
  map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | list }}"

# pg_basebackup command
pg_basebackup_cmd: /usr/pgsql-12/bin/pg_basebackup -R -D {{ PGDATA }}