---
# file: roles/edb_efm/tasks/main.yml

- import_tasks: setup_edbrepo.yml
  become: yes
  when: edb_repo
  tags: efm_install

- name: nodeips
  setup:
    gather_subset: network

- import_tasks: install_efm.yml
  become: yes
  tags:
  - efm_install

- import_tasks: create_efm_user.yml
  become: yes
  when: pg_repl_role == 'master'
  tags:
  - efm_config

- import_tasks: config_efm.yml
  become: yes
  tags:
  - efm_config

- meta: flush_handlers
  tags:
  - efm_config

- name: efm service started
  become: true
  systemd:
    name: "edb-efm-{{ EFM_VERSION }}"
    enabled: yes
    state: started
  tags:
  - efm_config