---
# file: roles/postgres-install/tasks/setup_pgrepo.yml

- name: Install edb official repo
  yum: 
    name: https://yum.enterprisedb.com/edbrepos/edb-repo-latest.noarch.rpm

- name: Set repo password
  replace:
    path: /etc/yum.repos.d/edb.repo
    regexp: "<username>:<password>"
    replace: "{{ edb_repo_user }}:{{ edb_repo_pass }}"