# This workflow will test Playbook with ANSIBL & LXD
name: Test playbook with Ansible and LXD

on:
  push:
    branches: [ half-baked ]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: sudo lxc version
    - run: |
        cat <<EOF | sudo lxd init --preseed
        config: {}
        networks:
        - config:
            ipv4.address: 10.246.23.1/24
            ipv4.nat: "true"
            ipv6.address: auto
          description: ""
          managed: false
          name: lxdbr0
          type: ""
        storage_pools:
        - config: {}
          description: ""
          name: default
          driver: dir
        profiles:
        - config: {}
          description: ""
          devices:
            eth0:
              name: eth0
              nictype: bridged
              parent: lxdbr0
              type: nic
            root:
              path: /
              pool: default
              type: disk
          name: default
        cluster: null
        EOF
    - run: sudo lxc launch images:centos/7 test
    - run: sleep 5; lxc list
    - run: echo "${{ secrets.VAULT_PASS }}" > .vault_pass
    - name: Provision Infra
      run: ansible-playbook playbook.yml -e @edb_cred.yml
    - run: sudo lxc list 
