# This workflow will provision AWS resources
name: Create AWS Infra

on:
  push:
    branches: [ half-baked ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Ansible Syntax
      run: ansible-playbook playbook.yml --syntax-check
    - name: Create Ansible Infra
      run: ansible-playbook playbook.yml -v