# This workflow will test Playbook with ANSIBL & LXD
name: Test playbook with Ansible and LXD

on:
  push:
    branches: [ half-baked ]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: sudo lxc version
    - run: |
        cat <<EOF | sudo lxd init --preseed
        config: {}
        networks:
        - config:
            ipv4.address: 10.246.23.1/24
            ipv4.nat: "true"
            ipv6.address: auto
          description: ""
          managed: false
          name: lxdbr0
          type: ""
        storage_pools:
        - config: {}
          description: ""
          name: default
          driver: dir
        profiles:
        - config: {}
          description: ""
          devices:
            eth0:
              name: eth0
              nictype: bridged
              parent: lxdbr0
              type: nic
            root:
              path: /
              pool: default
              type: disk
          name: default
        cluster: null
        EOF
    - run: sudo apt install python-netaddr
    - run: echo "${{ secrets.VAULT_PASS }}" > .vault_pass
    - name: Provision Infra
      run: sudo ansible-playbook playbook.yml -e @edb_cred.yml
    - run: sudo lxc list 
    - name: check efm status
      run: sudo lxc exec db01 -- /usr/edb/efm-4.0/bin/efm cluster-status efm
    - name: check replication on master
      run: sudo lxc exec db01 -- psql -U postgres -xc 'select * from pg_stat_replication;'
    - name: check switchover
      run: sudo lxc exec db01 -- /usr/edb/efm-4.0/bin/efm promote efm -switchover
    - name: check efm status
      run: sleep 30; sudo lxc exec db01 -- /usr/edb/efm-4.0/bin/efm cluster-status efm
    - name: check failover
      run: sudo lxc stop db02
    - name: check efm status
      run: sleep 30; sudo lxc exec db01 -- /usr/edb/efm-4.0/bin/efm cluster-status efm
      
